from rest_framework.routers import DefaultRouter
from api.blog.views import PostViewSet, CategoryViewSet, TagViewSet

# Create a router and register the viewsets
router = DefaultRouter()

# Register the viewsets with their respective base paths and viewset classes
router.register(r'posts', PostViewSet, basename='post')
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'tags', TagViewSet, basename='tag')

# The URL patterns will be automatically generated by the router
urlpatterns = router.urls
